networks:
  backend:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000  # Altere para o valor do seu 'id -u'
        GROUP_ID: 1000  # Altere para o valor do seu 'id -g'
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    env_file: .env
    environment:
      BUNDLE_GEMFILE: /app/Gemfile
    command: bin/docker-dev-start-web.sh
    networks:
      - backend
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: credito_poc_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  bundle:
  postgres_data:
  redis_data:
